### PR TITLE
Root relative paths using CARGO_MANIFEST_DIR

### LINKED ISSUE #34: In debug build, it should work, no matter which folder `cargo` is invoked from!
Try to run `cargo run --example basic` from the `examples` subfolder, it will crash.
The procmacro should make sure that it works, no matter where cargo is called from! 
(Also important for workspaces, where the exe could be in the toplevel or in a sub folder.)

### PR DESCRIPTION
**Pull request by Mcat12**
Fixes #34 and #99.

### CODE REVIEW

File: impl/src/lib.rs [hunk 1]
```diff
@@ -144,6 +144,16 @@ fn impl_rust_embed(ast: &syn::DeriveInput) -> TokenStream2 {
   #[cfg(feature = "interpolate-folder-path")]
   let folder_path = shellexpand::full(&folder_path).unwrap().to_string();
 
+  // Base relative paths on the Cargo.toml location
+  let folder_path = if Path::new(&folder_path).is_relative() {
+    Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
+      .join(folder_path)
+      .to_string_lossy()
```
Comment (paolobarbolini) [inline impl/src/lib.rs]: This would probably be better off if it were `.to_str().unwrap()`

We are already making sure strings are valid UTF-8 in the rest of the code so we shouldn't have to drop invalid characters here.
